on:
  workflow_call:

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v5

      - name: Install pre-commit
        run: |
          pipx install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
